--- 
title: "AP^&reg;^ Research Syllabus"
author: ""
date: 2019-07-25
site: bookdown::bookdown_site
output: 
  bookdown::gitbook:
    config:
      sharing: null
        # facebook: false
        # twitter: false
documentclass: article
fontsize: 11pt
geometry: margin=1in
bibliography: [book.bib, packages.bib]
csl: apa.csl
link-citations: yes
github-repo: apscholar/ap-research-syllabus
description: "This notebook includes a syllabus and detailed course schedule for AP Research"
always_allow_html: yes
---

```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(cache=FALSE, dev='png')
mon <- as.Date("2016-08-15")
# fri <- as.Date("2016-01-08")

advdate <- function(obj, adv) {
 tmon <- obj + 7*(adv-1)
 tfri <- obj + 4 + 7*(adv-1)
 tmon <- format(tmon, format="%m/%d")
 tfri <- format(tfri, format="%m/%d")
 zadv <- sprintf("%02d", adv)
 tmp <- paste("Week ",zadv,sep='',", ", tmon," - ",tfri)
 return(tmp)
}

library(RefManageR)
# library(knitcitations)
# library(rcrossref)
bib <- ReadBib("book.bib")
BibOptions(bib.style = "authoryear", style="markdown", first.inits=TRUE, max.names = 4, check.entries = FALSE)

#https://stackoverflow.com/questions/46260431/include-the-text-of-a-bibentry-in-the-rmarkdown-text-body-output
# library(bibtex)
# biblio <- bibtex::read.bib(file="book.bib")
```

\newpage
\hypersetup{linkcolor=blue}
# Course Description
**Prerequisite:** AP^&reg;^ Seminar  
AP^&reg;^ Research is a one-year course that culminates in a 4000- to 5000-word academic paper and a 20-minute presentation with oral defense. Students will learn the process of academic research as well as industry-aligned research tools.

